[project]
name = "odoo-addons-oca-l10n-switzerland"
version = "18.0.20250128.0"
dependencies = [
    "odoo-addon-l10n_ch_account_tags==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
